import type { ContenutoGioco } from "@/types/domain";

// Local seed of "Chi è più probabile?" questions. Original, all "Famiglia"/13+.
const raw: Array<[string, ContenutoGioco["intensita"], number]> = [
  ["Chi è più probabile che arrivi in ritardo al proprio matrimonio?", "Divertente", 0],
  ["Chi è più probabile che dimentichi dove ha parcheggiato?", "Tranquillo", 0],
  ["Chi è più probabile che diventi famoso?", "Tranquillo", 0],
  ["Chi è più probabile che rida nel momento sbagliato?", "Divertente", 0],
  ["Chi è più probabile che diventi milionario?", "Tranquillo", 0],
  ["Chi è più probabile che si perda in una città nuova?", "Tranquillo", 0],
  ["Chi è più probabile che mangi l'ultima fetta di pizza?", "Divertente", 0],
  ["Chi è più probabile che parli da solo?", "Divertente", 0],
  ["Chi è più probabile che diventi un influencer?", "Divertente", 0],
  ["Chi è più probabile che dimentichi il proprio compleanno?", "Tranquillo", 0],
  ["Chi è più probabile che canti sotto la doccia?", "Tranquillo", 0],
  ["Chi è più probabile che si addormenti al cinema?", "Tranquillo", 0],
  ["Chi è più probabile che inciampi sul nulla?", "Divertente", 0],
  ["Chi è più probabile che diventi il capo di tutti?", "Tranquillo", 0],
  ["Chi è più probabile che pianga guardando un film?", "Tranquillo", 0],
  ["Chi è più probabile che dimentichi un nome appena presentato?", "Tranquillo", 0],
  ["Chi è più probabile che adotti dieci gatti?", "Divertente", 0],
  ["Chi è più probabile che vinca a un gioco da tavolo?", "Tranquillo", 0],
  ["Chi è più probabile che faccia un viaggio all'ultimo minuto?", "Divertente", 13],
  ["Chi è più probabile che diventi uno chef?", "Tranquillo", 0],
  ["Chi è più probabile che risponda 'cinque minuti' e arrivi dopo un'ora?", "Divertente", 0],
  ["Chi è più probabile che si commuova per un cucciolo?", "Tranquillo", 0],
  ["Chi è più probabile che diventi famoso sui social?", "Divertente", 13],
  ["Chi è più probabile che dimentichi il telefono a casa?", "Tranquillo", 0],
  ["Chi è più probabile che organizzi la festa perfetta?", "Divertente", 13],
  ["Chi è più probabile che si metta a ballare per primo?", "Audace", 13],
  ["Chi è più probabile che racconti la stessa storia mille volte?", "Divertente", 0],
  ["Chi è più probabile che diventi un esploratore?", "Tranquillo", 0],
  ["Chi è più probabile che compri qualcosa di inutile online?", "Divertente", 13],
  ["Chi è più probabile che vinca un premio Nobel?", "Tranquillo", 0],
  ["Chi è più probabile che dimentichi le chiavi dentro casa?", "Tranquillo", 0],
  ["Chi è più probabile che canti a squarciagola in macchina?", "Divertente", 0],
  ["Chi è più probabile che diventi un comico?", "Divertente", 13],
  ["Chi è più probabile che faccia amicizia con uno sconosciuto?", "Divertente", 13],
  ["Chi è più probabile che si perda tra i social per ore?", "Divertente", 13],
  ["Chi è più probabile che diventi un maestro di cucina?", "Tranquillo", 0],
  ["Chi è più probabile che dica una battuta al momento sbagliato?", "Audace", 13],
  ["Chi è più probabile che collezioni qualcosa di strano?", "Divertente", 0],
  ["Chi è più probabile che dimentichi un appuntamento importante?", "Tranquillo", 13],
  ["Chi è più probabile che diventi la persona più organizzata del gruppo?", "Tranquillo", 0],
];

export const DOMANDE_PROBABILE: ContenutoGioco[] = raw.map(([prompt, intensita], i) => ({
  id: `prob-${i}`,
  gameType: "chi-e-piu-probabile",
  prompt,
  intensita,
}));
