import type { ImpostorWord } from "@/types/domain";

// Local seed of Impostor words. All original, family-safe by default.
// Difficulty roughly reflects how obscure/hard-to-describe the word is.
const raw: Array<[string, string]> = [
  ["Cane", "Animali"],
  ["Gatto", "Animali"],
  ["Elefante", "Animali"],
  ["Pinguino", "Animali"],
  ["Coccodrillo", "Animali"],
  ["Scoiattolo", "Animali"],
  ["Ornitorinco", "Animali"],
  ["Delfino", "Animali"],
  ["Pizza", "Cibo"],
  ["Gelato", "Cibo"],
  ["Lasagna", "Cibo"],
  ["Tiramisù", "Cibo"],
  ["Carciofo", "Cibo"],
  ["Bruschetta", "Cibo"],
  ["Cannolo", "Cibo"],
  ["Spaghetti", "Cibo"],
  ["Spiaggia", "Luoghi"],
  ["Montagna", "Luoghi"],
  ["Aeroporto", "Luoghi"],
  ["Biblioteca", "Luoghi"],
  ["Faro", "Luoghi"],
  ["Colosseo", "Luoghi"],
  ["Vulcano", "Luoghi"],
  ["Mercato", "Luoghi"],
  ["Medico", "Professioni"],
  ["Insegnante", "Professioni"],
  ["Astronauta", "Professioni"],
  ["Pompiere", "Professioni"],
  ["Archeologo", "Professioni"],
  ["Sommelier", "Professioni"],
  ["Giardiniere", "Professioni"],
  ["Cuoco", "Professioni"],
  ["Ombrello", "Oggetti"],
  ["Chiave", "Oggetti"],
  ["Bussola", "Oggetti"],
  ["Forbici", "Oggetti"],
  ["Clessidra", "Oggetti"],
  ["Zaino", "Oggetti"],
  ["Cuscino", "Oggetti"],
  ["Binocolo", "Oggetti"],
  ["Calcio", "Sport"],
  ["Nuoto", "Sport"],
  ["Scherma", "Sport"],
  ["Pallavolo", "Sport"],
  ["Arrampicata", "Sport"],
  ["Canottaggio", "Sport"],
  ["Tennis", "Sport"],
  ["Snowboard", "Sport"],
  ["Robot", "Tecnologia"],
  ["Drone", "Tecnologia"],
  ["Auricolari", "Tecnologia"],
  ["Stampante", "Tecnologia"],
  ["Realtà virtuale", "Tecnologia"],
  ["Chiavetta USB", "Tecnologia"],
  ["Chitarra", "Musica"],
  ["Batteria", "Musica"],
  ["Violino", "Musica"],
  ["Fisarmonica", "Musica"],
  ["Xilofono", "Musica"],
  ["Karaoke", "Musica"],
  ["Valigia", "Viaggi"],
  ["Passaporto", "Viaggi"],
  ["Tenda da campeggio", "Viaggi"],
  ["Crociera", "Viaggi"],
  ["Lavagna", "Scuola"],
  ["Zaino di scuola", "Scuola"],
  ["Compito in classe", "Scuola"],
  ["Ricreazione", "Scuola"],
];

export const IMPOSTOR_WORDS: ImpostorWord[] = raw.map(([prompt, categoria], i) => ({
  id: `imp-${i}`,
  gameType: "impostore",
  prompt,
  categoria,
  intensita: "Divertente",
}));

export const CATEGORIE_IMPOSTORE = Array.from(
  new Set(IMPOSTOR_WORDS.map((w) => w.categoria)),
);
