import type { ContenutoOV, Intensita } from "@/types/domain";

// Local seed for Obbligo o Verità. All original, natural Italian, safe.
// Truths and dares carry structured metadata used by filters and accessibility.

type T = [string, string, Intensita, number]; // prompt, cat, int, etaMin
// dare: prompt, cat, int, etaMin, timer, movimento, contatto, safeAlt
type D = [string, string, Intensita, number, number, boolean, boolean, string?];

const VERITA: T[] = [
  ["Qual è una piccola bugia che dici spesso?", "Personale", "Divertente", 13],
  ["Qual è stata la tua figuraccia più divertente?", "Divertente", "Divertente", 13],
  ["Quale abitudine vorresti cambiare?", "Personale", "Tranquillo", 0],
  ["Chi del gruppo conosci da più tempo?", "Amicizia", "Tranquillo", 0],
  ["Qual è una cosa che ti rende subito felice?", "Personale", "Tranquillo", 0],
  ["Quale talento vorresti avere?", "Creatività", "Tranquillo", 0],
  ["Qual è il messaggio più strano che hai mai inviato?", "Divertente", "Divertente", 13],
  ["Qual è una cosa che quasi nessuno sa di te?", "Personale", "Divertente", 13],
  ["Qual è il tuo ricordo più bello con qualcuno del gruppo?", "Amicizia", "Tranquillo", 0],
  ["Se potessi vivere in un cartone animato, quale sceglieresti?", "Divertente", "Tranquillo", 0],
  ["Qual è la cosa più coraggiosa che hai fatto?", "Personale", "Divertente", 13],
  ["Qual è il tuo piatto preferito in assoluto?", "Conoscersi meglio", "Tranquillo", 0],
  ["Cosa ti fa ridere ogni volta, anche se non dovrebbe?", "Divertente", "Divertente", 0],
  ["Qual è un sogno che vorresti realizzare?", "Personale", "Tranquillo", 0],
  ["Chi del gruppo sceglieresti come compagno di viaggio?", "Amicizia", "Divertente", 0],
  ["Qual è la materia scolastica che preferisci e perché?", "Scuola", "Tranquillo", 0],
  ["Qual è stata la lezione più noiosa della tua vita?", "Scuola", "Divertente", 0],
  ["Qual è un piccolo gesto che apprezzi molto negli altri?", "Amicizia", "Tranquillo", 0],
  ["Qual è la cosa più imbarazzante che hai detto per sbaglio?", "Imbarazzante", "Audace", 13],
  ["Se potessi cambiare nome, quale sceglieresti?", "Divertente", "Tranquillo", 0],
  ["Qual è una qualità che ammiri in una persona del gruppo?", "Amicizia", "Tranquillo", 0],
  ["Qual è la cosa più strana che hai mangiato?", "Divertente", "Divertente", 0],
  ["Qual è un tuo piccolo talento nascosto?", "Creatività", "Tranquillo", 0],
  ["Qual è la cosa più bella che qualcuno ti ha detto?", "Personale", "Tranquillo", 13],
  ["Qual è il tuo momento preferito della giornata?", "Conoscersi meglio", "Tranquillo", 0],
  ["Qual è una paura che vorresti superare?", "Personale", "Divertente", 13],
  ["Qual è la canzone che canti sempre a squarciagola?", "Divertente", "Divertente", 0],
  ["Se avessi un superpotere per un giorno, cosa faresti?", "Creatività", "Divertente", 0],
  ["Qual è la cosa più gentile che hai fatto per qualcuno?", "Amicizia", "Tranquillo", 0],
  ["Qual è un ricordo d'infanzia che ti fa sorridere?", "Conoscersi meglio", "Tranquillo", 0],
  ["Qual è la tua serie o film preferito del momento?", "Conoscersi meglio", "Tranquillo", 0],
  ["Cosa faresti se vincessi una giornata intera libera?", "Personale", "Tranquillo", 0],
  ["Qual è il complimento che ti fa più piacere ricevere?", "Personale", "Tranquillo", 13],
  ["Qual è la cosa più divertente successa a scuola?", "Scuola", "Divertente", 0],
  ["Chi del gruppo ti fa ridere di più?", "Gruppo", "Divertente", 0],
  ["Qual è una cosa nuova che vorresti imparare?", "Creatività", "Tranquillo", 0],
  ["Qual è il posto in cui ti senti più tranquillo?", "Personale", "Tranquillo", 0],
  ["Qual è stata la tua migliore idea mai avuta?", "Creatività", "Divertente", 13],
  ["Qual è la cosa più imbarazzante nel tuo telefono in questo momento?", "Imbarazzante", "Audace", 16],
  ["Qual è un difetto che sai di avere ma che accetti?", "Personale", "Audace", 16],
  ["Qual è la cotta più assurda che hai avuto?", "Relazioni", "Audace", 16],
  ["Cosa cerchi davvero in un'amicizia?", "Relazioni", "Tranquillo", 13],
  ["Qual è una cosa di cui vai particolarmente fiero?", "Personale", "Tranquillo", 0],
  ["Qual è il consiglio migliore che ti hanno dato?", "Conoscersi meglio", "Tranquillo", 0],
  ["Se dovessi descriverti con un'emoji, quale useresti?", "Divertente", "Tranquillo", 0],
  ["Qual è un momento in cui ti sei sentito davvero coraggioso?", "Personale", "Divertente", 13],
  ["Qual è la tradizione di famiglia che preferisci?", "Famiglia", "Tranquillo", 0],
  ["Chi in famiglia ti somiglia di più, secondo te?", "Famiglia", "Tranquillo", 0],
  ["Qual è la cosa più dolce che ha fatto un tuo amico per te?", "Amicizia", "Tranquillo", 0],
  ["Qual è una parola che usi troppo spesso?", "Divertente", "Divertente", 0],
  ["Qual è la sfida più grande che hai affrontato di recente?", "Personale", "Audace", 16],
  ["Se potessi dire una cosa a te stesso di un anno fa, quale sarebbe?", "Personale", "Tranquillo", 16],
  ["Qual è la cosa che ti mette di buon umore anche nelle giornate storte?", "Conoscersi meglio", "Tranquillo", 0],
  ["Qual è un sogno un po' folle che hai nel cassetto?", "Creatività", "Caotico", 13],
  ["Qual è stata la reazione più esagerata che hai avuto per una piccola cosa?", "Imbarazzante", "Caotico", 13],
];

const OBBLIGHI: D[] = [
  ["Imita un animale scelto dal gruppo per 20 secondi.", "Recitazione", "Divertente", 0, 20, true, false, "Descrivi un animale scelto dal gruppo con tre aggettivi."],
  ["Parla con un accento inventato fino al tuo prossimo turno.", "Divertente", "Divertente", 0, 0, false, false, "Racconta una breve storia con una voce buffa."],
  ["Fai una pubblicità improvvisata per un oggetto vicino a te.", "Creatività", "Divertente", 0, 30, false, false],
  ["Balla senza musica per 15 secondi.", "Movimento", "Divertente", 0, 15, true, false, "Canticchia una melodia allegra per 15 secondi."],
  ["Racconta una storia usando tre parole scelte dal gruppo.", "Creatività", "Divertente", 0, 30, false, false],
  ["Fai ridere il gruppo senza toccare nessuno.", "Divertente", "Divertente", 0, 30, false, false],
  ["Recita una scena drammatica leggendo il menu del telefono.", "Recitazione", "Divertente", 13, 30, false, false],
  ["Mantieni una posa scelta dal gruppo per 10 secondi.", "Movimento", "Divertente", 0, 10, true, false, "Scegli tu una posa e descrivila al gruppo."],
  ["Racconta una barzelletta al gruppo.", "Divertente", "Tranquillo", 0, 0, false, false],
  ["Fai il tuo miglior verso di un supereroe.", "Recitazione", "Divertente", 0, 15, false, false],
  ["Canta il ritornello di una canzone a tua scelta.", "Creatività", "Divertente", 0, 20, false, false, "Recita il testo del ritornello come una poesia."],
  ["Cammina attraverso la stanza come se sfilassi in passerella.", "Movimento", "Divertente", 0, 15, true, false, "Descrivi come cammineresti su una passerella."],
  ["Imita il modo di parlare di un personaggio famoso.", "Recitazione", "Divertente", 13, 20, false, false],
  ["Fai finta di essere un telecronista e commenta cosa succede nella stanza.", "Creatività", "Divertente", 0, 30, false, false],
  ["Descrivi la tua giornata usando solo mimo.", "Recitazione", "Divertente", 0, 30, true, false, "Descrivi la tua giornata in una sola frase."],
  ["Inventa un breve slogan per il gruppo.", "Gruppo", "Divertente", 0, 20, false, false],
  ["Parla per un minuto senza dire 'sì' e 'no'.", "Divertente", "Audace", 13, 60, false, false],
  ["Fai una smorfia buffa e mantienila per 10 secondi.", "Divertente", "Divertente", 0, 10, false, false],
  ["Racconta un aneddoto divertente su di te in 30 secondi.", "Personale", "Divertente", 13, 30, false, false],
  ["Imita come balleresti a un matrimonio.", "Movimento", "Caotico", 0, 15, true, false, "Racconta come immagini un matrimonio perfetto."],
  ["Fai il tuo miglior discorso motivazionale in 20 secondi.", "Recitazione", "Divertente", 0, 20, false, false],
  ["Descrivi un film famoso in modo così vago che gli altri devono indovinarlo.", "Gruppo", "Divertente", 0, 45, false, false],
  ["Inventa una nuova parola e spiegane il significato.", "Creatività", "Divertente", 0, 20, false, false],
  ["Fai finta di essere un robot fino al tuo prossimo turno.", "Recitazione", "Caotico", 0, 0, false, false],
  ["Racconta la trama di una favola nel modo più drammatico possibile.", "Recitazione", "Divertente", 0, 45, false, false],
  ["Fai tre complimenti sinceri a tre persone diverse del gruppo.", "Amicizia", "Tranquillo", 0, 0, false, false],
  ["Imita l'espressione di qualcuno che apre un regalo che non gli piace.", "Recitazione", "Divertente", 0, 15, false, false],
  ["Balla la tua mossa migliore per 10 secondi.", "Movimento", "Caotico", 0, 10, true, false, "Spiega a parole la tua mossa di ballo preferita."],
  ["Racconta una storia horror con oggetti della stanza come protagonisti.", "Creatività", "Audace", 13, 45, false, false],
  ["Fai finta di intervistare una persona del gruppo come una star.", "Gruppo", "Divertente", 0, 45, false, false],
  ["Canta 'Tanti auguri' nello stile di un cantante lirico.", "Creatività", "Divertente", 0, 20, false, false, "Recita il testo di 'Tanti auguri' come una poesia."],
  ["Cammina all'indietro attraverso la stanza in sicurezza.", "Movimento", "Divertente", 0, 15, true, false, "Descrivi cosa vedi dietro di te senza voltarti."],
  ["Improvvisa un dialogo tra due oggetti sul tavolo.", "Recitazione", "Divertente", 0, 30, false, false],
  ["Fai il verso di tre animali diversi di seguito.", "Divertente", "Divertente", 0, 15, false, false],
  ["Racconta come sarebbe la tua giornata perfetta in 30 secondi.", "Personale", "Tranquillo", 0, 30, false, false],
  ["Imita il tuo insegnante preferito (in modo gentile).", "Scuola", "Divertente", 0, 20, false, false],
  ["Fai una posa da statua e lascia che il gruppo ti dia un titolo.", "Movimento", "Divertente", 0, 10, true, false, "Proponi tu un titolo per una statua immaginaria."],
  ["Recita l'alfabeto come se fosse la scena più triste di un film.", "Recitazione", "Caotico", 0, 30, false, false],
  ["Inventa una canzone di dieci secondi su un oggetto vicino.", "Creatività", "Divertente", 0, 15, false, false],
  ["Fai finta di essere una guida turistica della stanza.", "Creatività", "Divertente", 0, 45, true, false, "Descrivi la stanza come se fosse un museo."],
  ["Mostra come reagiresti vincendo alla lotteria, senza parole.", "Recitazione", "Caotico", 0, 15, false, false],
  ["Racconta una bugia talmente assurda da far ridere tutti.", "Divertente", "Divertente", 0, 20, false, false],
  ["Imita un personaggio dei cartoni animati per 15 secondi.", "Recitazione", "Divertente", 0, 15, false, false],
  ["Fai il tifo per una squadra immaginaria come allo stadio.", "Movimento", "Caotico", 0, 15, true, false, "Inventa un coro da stadio per una squadra immaginaria."],
  ["Descrivi il tuo piatto preferito in modo così goloso da far venire fame a tutti.", "Divertente", "Divertente", 0, 30, false, false],
  ["Improvvisa il finale alternativo di una storia famosa.", "Creatività", "Divertente", 13, 45, false, false],
  ["Fai una faccia seria mentre gli altri provano a farti ridere per 20 secondi.", "Gruppo", "Caotico", 0, 20, false, false],
  ["Racconta cosa faresti se fossi invisibile per un'ora.", "Personale", "Audace", 13, 30, false, false],
  ["Imita il rumore di una tempesta usando solo la voce.", "Creatività", "Divertente", 0, 15, false, false],
  ["Fai un breve monologo da villain di un film.", "Recitazione", "Audace", 13, 30, false, false],
  ["Mostra la tua migliore mossa di arti marziali al rallentatore.", "Movimento", "Divertente", 0, 15, true, false, "Descrivi una mossa di arti marziali passo dopo passo."],
  ["Racconta una storia iniziando ogni frase con la lettera successiva dell'alfabeto.", "Creatività", "Caotico", 16, 60, false, false],
  ["Fai finta di essere un notiziario che annuncia una notizia buffa.", "Recitazione", "Divertente", 0, 30, false, false],
  ["Imita come si comporterebbe un gatto per 20 secondi.", "Recitazione", "Divertente", 0, 20, true, false, "Descrivi una giornata tipo vista dagli occhi di un gatto."],
  ["Inventa un ballo di gruppo di tre mosse e insegnalo agli altri.", "Movimento", "Caotico", 0, 30, true, false, "Descrivi tre mosse di ballo senza eseguirle."],
];

let idx = 0;
const truth = VERITA.map<ContenutoOV>(([prompt, categoria, intensita]) => ({
  id: `ov-t-${idx++}`,
  gameType: "obbligo-o-verita",
  tipo: "truth",
  prompt,
  categoria,
  intensita,
}));

const dare = OBBLIGHI.map<ContenutoOV>(
  ([prompt, categoria, intensita, , timer, mov, contatto, safe]) => ({
    id: `ov-d-${idx++}`,
    gameType: "obbligo-o-verita",
    tipo: "dare",
    prompt,
    categoria,
    intensita,
    timerConsigliato: timer,
    richiedeMovimento: mov,
    richiedeContatto: contatto,
    safeAlternative: safe,
    minGiocatori: 2,
  }),
);

export const CONTENUTI_OV: ContenutoOV[] = [...truth, ...dare];

export const CATEGORIE_OV = Array.from(new Set(CONTENUTI_OV.map((c) => c.categoria))).sort();
