/**
 * Generates supabase/seed/content.sql from the bundled Italian content.
 * The content modules only use `import type`, so importing them here pulls in
 * zero runtime dependencies (esbuild/tsx strips the type-only `@/` imports).
 *
 * Deterministic UUIDv5 ids (namespaced by the stable content id) make the seed
 * idempotent: re-running it upserts by primary key instead of duplicating.
 *
 * Run: npm run db:seed:sql
 */
import { createHash } from "node:crypto";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { IMPOSTOR_WORDS } from "../src/features/content/impostore";
import { DOMANDE_PROBABILE } from "../src/features/content/chi-e-piu-probabile";
import { CONTENUTI_OV } from "../src/features/content/obbligo-verita";
import { DOMANDE_PREFERIRESTI } from "../src/features/content/preferiresti";
import { STATEMENTS_NON_HO_MAI } from "../src/features/content/non-ho-mai";
import { SFIDE } from "../src/features/content/sfide";
import { IDENTITA } from "../src/features/content/indovina-chi";
import { CARTE_PROIBITE } from "../src/features/content/parola-proibita";
import { PAROLE_INDOVINA } from "../src/features/content/indovina-la-parola";

const NS = "6ba7b810-9dad-11d1-80b4-00c04fd430c8";

function uuidv5(name: string): string {
  const ns = Buffer.from(NS.replace(/-/g, ""), "hex");
  const h = createHash("sha1").update(ns).update(name).digest();
  const b = h.subarray(0, 16);
  b[6] = (b[6] & 0x0f) | 0x50;
  b[8] = (b[8] & 0x3f) | 0x80;
  const x = b.toString("hex");
  return `${x.slice(0, 8)}-${x.slice(8, 12)}-${x.slice(12, 16)}-${x.slice(16, 20)}-${x.slice(20, 32)}`;
}

const q = (s: string | undefined | null) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);
const arr = (a?: string[]) =>
  a && a.length ? `array[${a.map((w) => `'${w.replace(/'/g, "''")}'`).join(",")}]::text[]` : "null";
const cat = (c?: string) => (c ? `(select id from categories where nome = ${q(c)} limit 1)` : "null");

interface Row {
  srcId: string;
  gameType: string;
  contentType: string;
  prompt: string;
  answer?: string;
  forbidden?: string[];
  categoria?: string;
  hint?: string;
  intensita: string;
}

const rows: Row[] = [];

for (const w of IMPOSTOR_WORDS)
  rows.push({ srcId: w.id, gameType: "impostore", contentType: "word", prompt: w.prompt, categoria: w.categoria, intensita: w.intensita });

for (const d of DOMANDE_PROBABILE)
  rows.push({ srcId: d.id, gameType: "chi-e-piu-probabile", contentType: "prompt", prompt: d.prompt, intensita: d.intensita });

for (const c of CONTENUTI_OV)
  rows.push({ srcId: c.id, gameType: "obbligo-o-verita", contentType: c.tipo, prompt: c.prompt, answer: c.safeAlternative, categoria: c.categoria, intensita: c.intensita });

for (const p of DOMANDE_PREFERIRESTI)
  rows.push({ srcId: p.id, gameType: "preferiresti", contentType: "prompt", prompt: p.prompt, intensita: p.intensita });

for (const s of STATEMENTS_NON_HO_MAI)
  rows.push({ srcId: s.id, gameType: "non-ho-mai", contentType: "prompt", prompt: s.prompt, intensita: s.intensita });

for (const s of SFIDE)
  rows.push({ srcId: s.id, gameType: "sfide", contentType: "prompt", prompt: s.prompt, categoria: s.tipoSfida, intensita: s.intensita });

for (const i of IDENTITA)
  rows.push({ srcId: i.id, gameType: "indovina-chi", contentType: "identity", prompt: i.prompt, categoria: i.categoria, intensita: i.intensita });

for (const c of CARTE_PROIBITE)
  rows.push({ srcId: c.id, gameType: "parola-proibita", contentType: "forbidden", prompt: c.prompt, answer: c.answer, forbidden: c.forbiddenWords, categoria: c.categoria, intensita: c.intensita });

for (const p of PAROLE_INDOVINA)
  rows.push({ srcId: p.id, gameType: "indovina-la-parola", contentType: "word", prompt: p.prompt, categoria: p.categoria, hint: p.suggerimento, intensita: p.intensita });

const values = rows
  .map((r) => {
    const id = uuidv5(`${r.gameType}:${r.srcId}`);
    return `  ('${id}', ${q(r.gameType)}, ${q(r.contentType)}, ${q(r.prompt)}, ${q(r.answer)}, ${q(r.hint)}, ${arr(r.forbidden)}, ${cat(r.categoria)}, ${q(r.intensita)}::intensita, 'it', 'official'::source_type, true, 'approved'::content_status)`;
  })
  .join(",\n");

const sql = `-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand.
-- Idempotent seed of all official Italian content into game_content.
-- Deterministic UUIDv5 ids => safe to run multiple times (upsert on primary key).
-- Requires: 0001_init.sql applied, and categories seeded (supabase/seed/seed.sql).
-- Total rows: ${rows.length}

insert into game_content
  (id, game_type, content_type, prompt, answer, hint, forbidden_words, category_id,
   intensita, language, source_type, is_official, status)
values
${values}
on conflict (id) do update set
  game_type = excluded.game_type,
  content_type = excluded.content_type,
  prompt = excluded.prompt,
  answer = excluded.answer,
  forbidden_words = excluded.forbidden_words,
  category_id = excluded.category_id,
  intensita = excluded.intensita,
  is_official = true,
  source_type = 'official',
  status = 'approved',
  updated_at = now();
`;

const outDir = resolve(dirname(fileURLToPath(import.meta.url)), "../supabase/seed");
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "content.sql"), sql);

const byGame = rows.reduce<Record<string, number>>((a, r) => ((a[r.gameType] = (a[r.gameType] ?? 0) + 1), a), {});
console.log(`Wrote supabase/seed/content.sql with ${rows.length} rows:`);
for (const [g, n] of Object.entries(byGame)) console.log(`  ${g}: ${n}`);
